version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: python_app
    env_file:
      - .env  # Carregar variáveis do .env para o container app
    volumes:
      - .:/app
    command: ["python3", "postgres.py"]

volumes:
  postgres_data:
